import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import React, { useState } from "react";
import { useGetPokemonByNameQuery } from '../redux/services/pokemon'


const inter = Inter({ subsets: ['latin'] })



export default function Home({ pokemons }) {
  const [searchTerm, setSearchTerm] = useState("ivysaur");
  const handleChange = event => {
    let test = setSearchTerm(event.target.value);
    console.log(searchTerm);
  };
  const { data, error, isLoading } = useGetPokemonByNameQuery(searchTerm)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="App">
          <input
            type="text"
            placeholder="Search..."
            value={searchTerm}
            onChange={handleChange}
          />

          {error ? (
            <>Oh no, there was an error</>
          ) : isLoading ? (
            <>Loading...</>
          ) : data ? (
            <>
              <h3>{data.species ? data.species.name : ""}</h3>
              <img src={data.sprites ? data.sprites.front_shiny : ""} />
            </>
          ) : null}
        </div>
        <h1>Pokémon</h1>
        <ul>
          {pokemons.results.map((pokemon, index) => <li>
            <Link href={`/pokemon/${index + 1}`}>
              <h2>{pokemon.name}</h2>
            </Link>
          </li>)}
        </ul>
      </main>
    </>
  )
}


export async function getServerSideProps() {
  const pokemons = await fetch('https://pokeapi.co/api/v2/pokemon').then(r => r.json())
  return {
    props: { pokemons },
  }
}
